var Word = require("./word.js")
var inquirer = require("inquirer")

var randomWords = ["enchanting",
    "alert",
    "serve",
    "habitual",
    "toothsome",
    "harbor",
    "late",
    "travel",
    "trucks",
    "lying",
    "lettuce",
    "bedroom",
    "workable",
    "wobble",
    "machine",
    "warn",
    "pathetic",
    "wire",
    "real",
    "ubiquitous",
    "blushing",
    "disappear",
    "supreme",
    "ants",
    "number",
    "need",
    "straw",
    "attract",
    "judge",
    "pocket",
    "help",
    "lame",
    "scarecrow",
    "arrest",
    "doctor",
    "glamorous",
    "observe",
    "tangy",
    "delirious",
    "mature",
    "legal",
    "goofy",
    "dependent",
    "jumpy",
    "inject",
    "crabby",
    "poison",
    "settle",
    "pies",
    "murder",
    "wander",
    "tow",
    "onerous",
    "question",
    "rail",
    "woebegone",
    "leg",
    "act",
    "stamp",
    "hope",
    "ink",
    "accurate",
    "man",
    "holistic",
    "flaky",
    "tested",
    "slimy",
    "evanescent",
    "advise",
    "frightening",
    "suffer",
    "kindhearted",
    "tedious",
    "shelf",
    "challenge",
    "sick",
    "sneeze",
    "waste",
    "deranged",
    "capricious",
    "tendency",
    "tan",
    "object",
    "change",
    "connect",
    "growth",
    "creator",
    "turn",
    "uttermost",
    "sidewalk",
    "grumpy",
    "soap",
    "horrible",
    "sneaky",
    "stimulating",
    "gorgeous",
    "spotted",
    "equable",
    "hug",
    "force",
    "ad hoc",
    "cough",
    "cloistered",
    "chalk",
    "railway",
    "pedal",
    "yam",
    "madly",
    "finger",
    "kiss",
    "typical",
    "miscreant",
    "nest",
    "stroke",
    "door",
    "bent",
    "abhorrent",
    "card",
    "wave",
    "rustic",
    "march",
    "suspect",
    "hunt",
    "spell",
    "mom",
    "upset",
    "unfasten",
    "grade",
    "maniacal",
    "fruit",
    "unruly",
    "aspiring",
    "impulse",
    "breezy",
    "sturdy",
    "brake",
    "space",
    "discussion",
    "illegal",
    "eager",
    "jaded",
    "ahead",
    "gaze",
    "describe",
    "step",
    "oval",
    "horse",
    "accessible",
    "grate",
    "sneeze",
    "lackadaisical",
    "alcoholic",
    "boundless",
    "numerous",
    "scarf",
    "interest",
    "spectacular",
    "memorise",
    "step",
    "flag",
    "eggnog",
    "fade",
    "hour",
    "pipe",
    "nerve",
    "rotten",
    "friends",
    "materialistic",
    "end",
    "languid",
    "consider",
    "ill-fated",
    "eatable",
    "collar",
    "bells",
    "office",
    "offer",
    "unsightly",
    "plastic",
    "square",
    "abstracted",
    "anxious",
    "brake",
    "squalid",
    "abject",
    "distance",
    "yarn",
    "week",
    "person",
    "ship",
    "pencil",
    "drum",
    "complain",
    "tickle",
    "obtainable",
    "vast",
    "creepy",
    "celery",
    "noiseless",
    "milky",
    "heat",
    "thankful",
    "amuck",
    "wrap",
    "can",
    "head",
    "little",
    "vase",
    "skin",
    "smoke",
    "pleasant",
    "mess up",
    "bless",
    "meeting",
    "steel",
    "oranges",
    "gratis",
    "reduce",
    "general",
    "boiling",
    "whip",
    "vague",
    "smelly",
    "cover",
    "waggish",
    "dark",
    "lucky",
    "fowl",
    "victorious",
    "confused",
    "wish",
    "uppity",
    "battle",
    "honey",
    "lewd",
    "coil",
    "testy",
    "observant",
    "nose",
    "spark",
    "tricky",
    "ground",
    "power",
    "listen",
    "screeching",
    "amusement",
    "redundant",
    "historical",
    "rule",
    "ripe"
]

var word

function createWord(){
    word = new Word(randomWords[Math.floor(Math.random() * 250)])
    word.populateLettersArr()
}

function promptUser() {
    console.log("")
    console.log("Guesses Remaining: " + word.guessesRemaining)
    console.log("")
    console.log(word.displayWord())
    console.log("")
    inquirer
        .prompt([{
            type: "input",
            message: "What is your guess?",
            name: "guess",
            validate: function validateAns(guess){
                if(guess.length != 1){
                    console.log("\nEnter only one letter.")
                }
                return guess.length == 1
            }
        }])
        .then(function (res) {
            word.guess(res.guess)

            if (word.guessesRemaining && word.correctCount < word.letters.length) {
                promptUser()
            } else if (word.guessesRemaining == 0) {
                console.log("Out of guesses! The correct word is '" + word.whichWord() + "'.")
                playAgain()
            } else {
                console.log("Correct!")
                playAgain()
            }
        })
}

function playAgain() {
    inquirer
        .prompt([{
            type: "confirm",
            message: "Play again?",
            name: "confirm",
            default: true
        }])
        .then(function (response) {
            if (response.confirm) {
                createWord()
                promptUser()
            }
        })
}

createWord()
promptUser()